framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async_email_register_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: email_register_exchange
                    queues:
                        email_register_queue: ~

            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            'App\Message\SendRegisterEmail': async_email_register_transport
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
