# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        public_avatar_adapter:
            local:
                location: '%kernel.project_dir%/public/uploads'
        public_map_adapter:
            local:
                location: '%kernel.project_dir%/public/uploads'
    filesystems:
        public_avatar_filesystem:
            adapter: public_avatar_adapter
            alias: League\Flysystem\AvatarFilesystem
        public_map_filesystem:
            adapter: public_map_adapter
            alias: League\Flysystem\MapFilesystem