# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    #router.request_context.scheme: '%env(SITE_BASE_SCHEME)%'
    #router.request_context.host: '%env(SITE_BASE_HOST)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $publicAvatarFilesystem: '@oneup_flysystem.public_avatar_filesystem_filesystem'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.repository.menu:
        class: App\Repository\MenuRepository


    app.menu_builder:
        class: App\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@app.repository.menu"]
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: main } # The alias is what is used to retrieve the menu

    App\Form\LoginFormType:
        arguments:
            $appCsrfToken: '%env(CSRF_TOKEN)%'

    App\Security\LoginFormAuthenticator:
        arguments:
            $appCsrfToken: '%env(CSRF_TOKEN)%'

    App\Form\RegisterFormType:
        arguments:
            $appCsrfToken: '%env(CSRF_TOKEN)'

    App\Form\Avatar\CreateAvatarFormType:
        arguments:
            $appCsrfToken: '%env(CSRF_TOKEN)'

    App\Controller\SecurityController:
        arguments:
            $emailVerifyKey: '%env(EMAIL_VERIFY_KEY)%'

    App\Service\Mailer:
        arguments:
            $mailAddress: '%env(SITE_EMAIL_ADDRESS)%'
            $mailOwner: '%env(SITE_EMAIL_OWNER)%'